#ifndef _SYSTEM_CONFIG_H
#define _SYSTEM_CONFIG_H
/* Avoid superfluous warning messages. */
#define _PLIB_UNSUPPORTED

/* TMR Driver Configuration Options */
#define DRV_TMR_INSTANCES_NUMBER 1
#define DRV_TMR_INTERRUPT_MODE false
#define DRV_TMR_CLIENTS_NUMBER 1
#define DRV_TMR_COUNT_WIDTH 16
#define DRV_TMR_ALARM_ENABLE
#define DRV_TMR_ALARM_PERIODIC true

/* System Clock Frequency */
#define SYS_CLOCK_FREQENCY (200000000UL)

/* TMR Driver Initialization Data */
#define APP_TMR_DRV_INDEX 0
#define APP_TMR_DRV_POWER_MODE SYS_MODULE_POWER_RUN_FULL
#define APP_TMR_DRV_HW_ID TMR_ID_2
#define APP_TMR_DRV_CLOCK_SOURCE DRV_TMR_CLKSOURCE_INTERNAL
#define APP_TMR_DRV_PRESCALE TMR_PRESCALE_VALUE_8
#define APP_TMR_DRV_INT_SOURCE INT_SOURCE_TIMER_2
#define APP_TMR_DRV_OPERATION_MODE DRV_TMR_OPERATION_MODE_16_BIT

/* Clock System Service Configuration */
#define SYS_CLK_CONFIG_PRIMARY_XTAL (24000000UL)
#define SYS_CLK_CONFIG_SECONDARY_XTAL (32768UL)
#define SYS_CLK_CONFIG_SYSPLL_INP_DIVISOR 3
#define SYS_CLK_CONFIG_FREQ_ERROR_LIMIT 10

/* Application Configuration */
#define APP_TMR_ALARM_PERIOD 0xF424
#define APP_TMR_ALARM_COUNT_MAX 10
#define APP_TMR_ALARM_COUNT_LED_ON 5
#define APP_LED_PORT PORT_CHANNEL_A
#define APP_LED_PIN PORTS_BIT_POS_6

#endif /* _SYSTEM_CONFIG_H */